//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/6/2021 9:11:38 PM
namespace Microsoft.Dynamics.DataEntities
{
        /// <summary>
        /// There are no comments for AssetLeaseAccountingFrameworkType in the schema.
        /// </summary>
    public enum AssetLeaseAccountingFrameworkType
    {
        IFRS16 = 0,
        ASC842 = 1,
        CashBasis = 2,
        ASC840 = 3,
        IAS17 = 4
    }
}
