//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/28/2021 8:55:09 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for EcoResVariantConfigurationTechnologyType in the schema.
    /// </summary>
    public enum EcoResVariantConfigurationTechnologyType
    {
        PredefinedVariants = 1,
        DimensionBased = 2,
        ConstraintBased = 4
    }
}
