//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/28/2021 8:55:09 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for EngineeringChangeOrderProductRouteOperationV2Single in the schema.
    /// </summary>
    public partial class EngineeringChangeOrderProductRouteOperationV2Single : global::Microsoft.OData.Client.DataServiceQuerySingle<EngineeringChangeOrderProductRouteOperationV2>
    {
        /// <summary>
        /// Initialize a new EngineeringChangeOrderProductRouteOperationV2Single object.
        /// </summary>
        public EngineeringChangeOrderProductRouteOperationV2Single(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EngineeringChangeOrderProductRouteOperationV2Single object.
        /// </summary>
        public EngineeringChangeOrderProductRouteOperationV2Single(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new EngineeringChangeOrderProductRouteOperationV2Single object.
        /// </summary>
        public EngineeringChangeOrderProductRouteOperationV2Single(global::Microsoft.OData.Client.DataServiceQuerySingle<EngineeringChangeOrderProductRouteOperationV2> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for EngineeringChangeOrderProductRouteHeaderV2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2Single EngineeringChangeOrderProductRouteHeaderV2
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._EngineeringChangeOrderProductRouteHeaderV2 == null))
                {
                    this._EngineeringChangeOrderProductRouteHeaderV2 = new global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2Single(this.Context, GetPath("EngineeringChangeOrderProductRouteHeaderV2"));
                }
                return this._EngineeringChangeOrderProductRouteHeaderV2;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2Single _EngineeringChangeOrderProductRouteHeaderV2;
        /// <summary>
        /// There are no comments for EngineeringChangeOrderProductRouteOperationPropertiesV2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2> EngineeringChangeOrderProductRouteOperationPropertiesV2
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._EngineeringChangeOrderProductRouteOperationPropertiesV2 == null))
                {
                    this._EngineeringChangeOrderProductRouteOperationPropertiesV2 = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2>(GetPath("EngineeringChangeOrderProductRouteOperationPropertiesV2"));
                }
                return this._EngineeringChangeOrderProductRouteOperationPropertiesV2;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2> _EngineeringChangeOrderProductRouteOperationPropertiesV2;
    }
    /// <summary>
    /// There are no comments for EngineeringChangeOrderProductRouteOperationV2 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// dataAreaId
    /// EngineeringChangeOrderNumber
    /// EngineeringChangeOrderProductLineNumber
    /// EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber
    /// OperationNumber
    /// OperationPriority
    /// ChangeType
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "EngineeringChangeOrderNumber", "EngineeringChangeOrderProductLineNumber", "EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber", "OperationNumber", "OperationPriority", "ChangeType")]
    [global::Microsoft.OData.Client.EntitySet("EngineeringChangeOrderProductRouteOperationsV2")]
    public partial class EngineeringChangeOrderProductRouteOperationV2 : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EngineeringChangeOrderProductRouteOperationV2 object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of dataAreaId.</param>
        /// <param name="engineeringChangeOrderNumber">Initial value of EngineeringChangeOrderNumber.</param>
        /// <param name="engineeringChangeOrderProductLineNumber">Initial value of EngineeringChangeOrderProductLineNumber.</param>
        /// <param name="engineeringChangeOrderProductRouteHeaderCreationSequenceNumber">Initial value of EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber.</param>
        /// <param name="operationNumber">Initial value of OperationNumber.</param>
        /// <param name="accumulatedScrapPercentage">Initial value of AccumulatedScrapPercentage.</param>
        /// <param name="operationSequence">Initial value of OperationSequence.</param>
        /// <param name="nextRouteOperationNumber">Initial value of NextRouteOperationNumber.</param>
        /// <param name="scrapPercentage">Initial value of ScrapPercentage.</param>
        /// <param name="engineeringChangeOrderProductRouteHeaderV2">Initial value of EngineeringChangeOrderProductRouteHeaderV2.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static EngineeringChangeOrderProductRouteOperationV2 CreateEngineeringChangeOrderProductRouteOperationV2(string dataAreaId, 
                    string engineeringChangeOrderNumber, 
                    decimal engineeringChangeOrderProductLineNumber, 
                    int engineeringChangeOrderProductRouteHeaderCreationSequenceNumber, 
                    int operationNumber, 
                    decimal accumulatedScrapPercentage, 
                    int operationSequence, 
                    int nextRouteOperationNumber, 
                    decimal scrapPercentage, 
                    global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2 engineeringChangeOrderProductRouteHeaderV2)
        {
            EngineeringChangeOrderProductRouteOperationV2 engineeringChangeOrderProductRouteOperationV2 = new EngineeringChangeOrderProductRouteOperationV2();
            engineeringChangeOrderProductRouteOperationV2.dataAreaId = dataAreaId;
            engineeringChangeOrderProductRouteOperationV2.EngineeringChangeOrderNumber = engineeringChangeOrderNumber;
            engineeringChangeOrderProductRouteOperationV2.EngineeringChangeOrderProductLineNumber = engineeringChangeOrderProductLineNumber;
            engineeringChangeOrderProductRouteOperationV2.EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber = engineeringChangeOrderProductRouteHeaderCreationSequenceNumber;
            engineeringChangeOrderProductRouteOperationV2.OperationNumber = operationNumber;
            engineeringChangeOrderProductRouteOperationV2.AccumulatedScrapPercentage = accumulatedScrapPercentage;
            engineeringChangeOrderProductRouteOperationV2.OperationSequence = operationSequence;
            engineeringChangeOrderProductRouteOperationV2.NextRouteOperationNumber = nextRouteOperationNumber;
            engineeringChangeOrderProductRouteOperationV2.ScrapPercentage = scrapPercentage;
            if ((engineeringChangeOrderProductRouteHeaderV2 == null))
            {
                throw new global::System.ArgumentNullException("engineeringChangeOrderProductRouteHeaderV2");
            }
            engineeringChangeOrderProductRouteOperationV2.EngineeringChangeOrderProductRouteHeaderV2 = engineeringChangeOrderProductRouteHeaderV2;
            return engineeringChangeOrderProductRouteOperationV2;
        }
        /// <summary>
        /// There are no comments for Property dataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "dataAreaId is required.")]
        public virtual string dataAreaId
        {
            get
            {
                return this._dataAreaId;
            }
            set
            {
                this.OndataAreaIdChanging(value);
                this._dataAreaId = value;
                this.OndataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _dataAreaId;
        partial void OndataAreaIdChanging(string value);
        partial void OndataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EngineeringChangeOrderNumber is required.")]
        public virtual string EngineeringChangeOrderNumber
        {
            get
            {
                return this._EngineeringChangeOrderNumber;
            }
            set
            {
                this.OnEngineeringChangeOrderNumberChanging(value);
                this._EngineeringChangeOrderNumber = value;
                this.OnEngineeringChangeOrderNumberChanged();
                this.OnPropertyChanged("EngineeringChangeOrderNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EngineeringChangeOrderNumber;
        partial void OnEngineeringChangeOrderNumberChanging(string value);
        partial void OnEngineeringChangeOrderNumberChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderProductLineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EngineeringChangeOrderProductLineNumber is required.")]
        public virtual decimal EngineeringChangeOrderProductLineNumber
        {
            get
            {
                return this._EngineeringChangeOrderProductLineNumber;
            }
            set
            {
                this.OnEngineeringChangeOrderProductLineNumberChanging(value);
                this._EngineeringChangeOrderProductLineNumber = value;
                this.OnEngineeringChangeOrderProductLineNumberChanged();
                this.OnPropertyChanged("EngineeringChangeOrderProductLineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _EngineeringChangeOrderProductLineNumber;
        partial void OnEngineeringChangeOrderProductLineNumberChanging(decimal value);
        partial void OnEngineeringChangeOrderProductLineNumberChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber is required.")]
        public virtual int EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber
        {
            get
            {
                return this._EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber;
            }
            set
            {
                this.OnEngineeringChangeOrderProductRouteHeaderCreationSequenceNumberChanging(value);
                this._EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber = value;
                this.OnEngineeringChangeOrderProductRouteHeaderCreationSequenceNumberChanged();
                this.OnPropertyChanged("EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _EngineeringChangeOrderProductRouteHeaderCreationSequenceNumber;
        partial void OnEngineeringChangeOrderProductRouteHeaderCreationSequenceNumberChanging(int value);
        partial void OnEngineeringChangeOrderProductRouteHeaderCreationSequenceNumberChanged();
        /// <summary>
        /// There are no comments for Property OperationNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "OperationNumber is required.")]
        public virtual int OperationNumber
        {
            get
            {
                return this._OperationNumber;
            }
            set
            {
                this.OnOperationNumberChanging(value);
                this._OperationNumber = value;
                this.OnOperationNumberChanged();
                this.OnPropertyChanged("OperationNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _OperationNumber;
        partial void OnOperationNumberChanging(int value);
        partial void OnOperationNumberChanged();
        /// <summary>
        /// There are no comments for Property OperationPriority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RouteOprPriority> OperationPriority
        {
            get
            {
                return this._OperationPriority;
            }
            set
            {
                this.OnOperationPriorityChanging(value);
                this._OperationPriority = value;
                this.OnOperationPriorityChanged();
                this.OnPropertyChanged("OperationPriority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RouteOprPriority> _OperationPriority;
        partial void OnOperationPriorityChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RouteOprPriority> value);
        partial void OnOperationPriorityChanged();
        /// <summary>
        /// There are no comments for Property ChangeType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.EngChgEcmChangeTypes> ChangeType
        {
            get
            {
                return this._ChangeType;
            }
            set
            {
                this.OnChangeTypeChanging(value);
                this._ChangeType = value;
                this.OnChangeTypeChanged();
                this.OnPropertyChanged("ChangeType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.EngChgEcmChangeTypes> _ChangeType;
        partial void OnChangeTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.EngChgEcmChangeTypes> value);
        partial void OnChangeTypeChanged();
        /// <summary>
        /// There are no comments for Property AccumulatedScrapPercentage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AccumulatedScrapPercentage is required.")]
        public virtual decimal AccumulatedScrapPercentage
        {
            get
            {
                return this._AccumulatedScrapPercentage;
            }
            set
            {
                this.OnAccumulatedScrapPercentageChanging(value);
                this._AccumulatedScrapPercentage = value;
                this.OnAccumulatedScrapPercentageChanged();
                this.OnPropertyChanged("AccumulatedScrapPercentage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _AccumulatedScrapPercentage;
        partial void OnAccumulatedScrapPercentageChanging(decimal value);
        partial void OnAccumulatedScrapPercentageChanged();
        /// <summary>
        /// There are no comments for Property OperationSequence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "OperationSequence is required.")]
        public virtual int OperationSequence
        {
            get
            {
                return this._OperationSequence;
            }
            set
            {
                this.OnOperationSequenceChanging(value);
                this._OperationSequence = value;
                this.OnOperationSequenceChanged();
                this.OnPropertyChanged("OperationSequence");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _OperationSequence;
        partial void OnOperationSequenceChanging(int value);
        partial void OnOperationSequenceChanged();
        /// <summary>
        /// There are no comments for Property NextRouteOperationNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NextRouteOperationNumber is required.")]
        public virtual int NextRouteOperationNumber
        {
            get
            {
                return this._NextRouteOperationNumber;
            }
            set
            {
                this.OnNextRouteOperationNumberChanging(value);
                this._NextRouteOperationNumber = value;
                this.OnNextRouteOperationNumberChanged();
                this.OnPropertyChanged("NextRouteOperationNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _NextRouteOperationNumber;
        partial void OnNextRouteOperationNumberChanging(int value);
        partial void OnNextRouteOperationNumberChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderProductRouteId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string EngineeringChangeOrderProductRouteId
        {
            get
            {
                return this._EngineeringChangeOrderProductRouteId;
            }
            set
            {
                this.OnEngineeringChangeOrderProductRouteIdChanging(value);
                this._EngineeringChangeOrderProductRouteId = value;
                this.OnEngineeringChangeOrderProductRouteIdChanged();
                this.OnPropertyChanged("EngineeringChangeOrderProductRouteId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EngineeringChangeOrderProductRouteId;
        partial void OnEngineeringChangeOrderProductRouteIdChanging(string value);
        partial void OnEngineeringChangeOrderProductRouteIdChanged();
        /// <summary>
        /// There are no comments for Property ScrapPercentage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ScrapPercentage is required.")]
        public virtual decimal ScrapPercentage
        {
            get
            {
                return this._ScrapPercentage;
            }
            set
            {
                this.OnScrapPercentageChanging(value);
                this._ScrapPercentage = value;
                this.OnScrapPercentageChanged();
                this.OnPropertyChanged("ScrapPercentage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _ScrapPercentage;
        partial void OnScrapPercentageChanging(decimal value);
        partial void OnScrapPercentageChanged();
        /// <summary>
        /// There are no comments for Property OperationRateMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.JmgJobPayTypeEnum> OperationRateMethod
        {
            get
            {
                return this._OperationRateMethod;
            }
            set
            {
                this.OnOperationRateMethodChanging(value);
                this._OperationRateMethod = value;
                this.OnOperationRateMethodChanged();
                this.OnPropertyChanged("OperationRateMethod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.JmgJobPayTypeEnum> _OperationRateMethod;
        partial void OnOperationRateMethodChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.JmgJobPayTypeEnum> value);
        partial void OnOperationRateMethodChanged();
        /// <summary>
        /// There are no comments for Property NextOperationLinkType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.SchedJobLinkType> NextOperationLinkType
        {
            get
            {
                return this._NextOperationLinkType;
            }
            set
            {
                this.OnNextOperationLinkTypeChanging(value);
                this._NextOperationLinkType = value;
                this.OnNextOperationLinkTypeChanged();
                this.OnPropertyChanged("NextOperationLinkType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.SchedJobLinkType> _NextOperationLinkType;
        partial void OnNextOperationLinkTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.SchedJobLinkType> value);
        partial void OnNextOperationLinkTypeChanged();
        /// <summary>
        /// There are no comments for Property OperationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string OperationId
        {
            get
            {
                return this._OperationId;
            }
            set
            {
                this.OnOperationIdChanging(value);
                this._OperationId = value;
                this.OnOperationIdChanged();
                this.OnPropertyChanged("OperationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OperationId;
        partial void OnOperationIdChanging(string value);
        partial void OnOperationIdChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderProductRouteHeaderV2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EngineeringChangeOrderProductRouteHeaderV2 is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2 EngineeringChangeOrderProductRouteHeaderV2
        {
            get
            {
                return this._EngineeringChangeOrderProductRouteHeaderV2;
            }
            set
            {
                this.OnEngineeringChangeOrderProductRouteHeaderV2Changing(value);
                this._EngineeringChangeOrderProductRouteHeaderV2 = value;
                this.OnEngineeringChangeOrderProductRouteHeaderV2Changed();
                this.OnPropertyChanged("EngineeringChangeOrderProductRouteHeaderV2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2 _EngineeringChangeOrderProductRouteHeaderV2;
        partial void OnEngineeringChangeOrderProductRouteHeaderV2Changing(global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteHeaderV2 value);
        partial void OnEngineeringChangeOrderProductRouteHeaderV2Changed();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderProductRouteOperationPropertiesV2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2> EngineeringChangeOrderProductRouteOperationPropertiesV2
        {
            get
            {
                return this._EngineeringChangeOrderProductRouteOperationPropertiesV2;
            }
            set
            {
                this.OnEngineeringChangeOrderProductRouteOperationPropertiesV2Changing(value);
                this._EngineeringChangeOrderProductRouteOperationPropertiesV2 = value;
                this.OnEngineeringChangeOrderProductRouteOperationPropertiesV2Changed();
                this.OnPropertyChanged("EngineeringChangeOrderProductRouteOperationPropertiesV2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2> _EngineeringChangeOrderProductRouteOperationPropertiesV2 = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnEngineeringChangeOrderProductRouteOperationPropertiesV2Changing(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderProductRouteOperationPropertiesV2> value);
        partial void OnEngineeringChangeOrderProductRouteOperationPropertiesV2Changed();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
