//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/20/2021 5:35:39 PM
namespace Microsoft.Dynamics.DataEntities
{
        /// <summary>
        /// There are no comments for EngineeringChangeOrderDependencyActionSingle in the schema.
        /// </summary>
    public partial class EngineeringChangeOrderDependencyActionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<EngineeringChangeOrderDependencyAction>
    {
        /// <summary>
        /// Initialize a new EngineeringChangeOrderDependencyActionSingle object.
        /// </summary>
        public EngineeringChangeOrderDependencyActionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EngineeringChangeOrderDependencyActionSingle object.
        /// </summary>
        public EngineeringChangeOrderDependencyActionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new EngineeringChangeOrderDependencyActionSingle object.
        /// </summary>
        public EngineeringChangeOrderDependencyActionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<EngineeringChangeOrderDependencyAction> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for EngineeringChangeOrderDependency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependencySingle EngineeringChangeOrderDependency
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._EngineeringChangeOrderDependency == null))
                {
                    this._EngineeringChangeOrderDependency = new global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependencySingle(this.Context, GetPath("EngineeringChangeOrderDependency"));
                }
                return this._EngineeringChangeOrderDependency;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependencySingle _EngineeringChangeOrderDependency;
        /// <summary>
        /// There are no comments for ProcessorWorker in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.WorkerSingle ProcessorWorker
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ProcessorWorker == null))
                {
                    this._ProcessorWorker = new global::Microsoft.Dynamics.DataEntities.WorkerSingle(this.Context, GetPath("ProcessorWorker"));
                }
                return this._ProcessorWorker;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.WorkerSingle _ProcessorWorker;
    }
        /// <summary>
        /// There are no comments for EngineeringChangeOrderDependencyAction in the schema.
        /// </summary>
    /// <KeyProperties>
    /// ActionClassName
    /// DependentProductNumber
    /// DependencyLegalEntityId
    /// DependencyTransactionDescription
    /// EngineeringChangeOrderNumber
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ActionClassName", "DependentProductNumber", "DependencyLegalEntityId", "DependencyTransactionDescription", "EngineeringChangeOrderNumber")]
    [global::Microsoft.OData.Client.EntitySet("EngineeringChangeOrderDependencyActions")]
    public partial class EngineeringChangeOrderDependencyAction : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EngineeringChangeOrderDependencyAction object.
        /// </summary>
        /// <param name="actionClassName">Initial value of ActionClassName.</param>
        /// <param name="dependentProductNumber">Initial value of DependentProductNumber.</param>
        /// <param name="dependencyLegalEntityId">Initial value of DependencyLegalEntityId.</param>
        /// <param name="dependencyTransactionDescription">Initial value of DependencyTransactionDescription.</param>
        /// <param name="engineeringChangeOrderNumber">Initial value of EngineeringChangeOrderNumber.</param>
        /// <param name="processedDateTime">Initial value of ProcessedDateTime.</param>
        /// <param name="engineeringChangeOrderDependency">Initial value of EngineeringChangeOrderDependency.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static EngineeringChangeOrderDependencyAction CreateEngineeringChangeOrderDependencyAction(string actionClassName, 
                    string dependentProductNumber, 
                    string dependencyLegalEntityId, 
                    string dependencyTransactionDescription, 
                    string engineeringChangeOrderNumber, 
                    global::System.DateTimeOffset processedDateTime, 
                    global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependency engineeringChangeOrderDependency)
        {
            EngineeringChangeOrderDependencyAction engineeringChangeOrderDependencyAction = new EngineeringChangeOrderDependencyAction();
            engineeringChangeOrderDependencyAction.ActionClassName = actionClassName;
            engineeringChangeOrderDependencyAction.DependentProductNumber = dependentProductNumber;
            engineeringChangeOrderDependencyAction.DependencyLegalEntityId = dependencyLegalEntityId;
            engineeringChangeOrderDependencyAction.DependencyTransactionDescription = dependencyTransactionDescription;
            engineeringChangeOrderDependencyAction.EngineeringChangeOrderNumber = engineeringChangeOrderNumber;
            engineeringChangeOrderDependencyAction.ProcessedDateTime = processedDateTime;
            if ((engineeringChangeOrderDependency == null))
            {
                throw new global::System.ArgumentNullException("engineeringChangeOrderDependency");
            }
            engineeringChangeOrderDependencyAction.EngineeringChangeOrderDependency = engineeringChangeOrderDependency;
            return engineeringChangeOrderDependencyAction;
        }
        /// <summary>
        /// There are no comments for Property ActionClassName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ActionClassName
        {
            get
            {
                return this._ActionClassName;
            }
            set
            {
                this.OnActionClassNameChanging(value);
                this._ActionClassName = value;
                this.OnActionClassNameChanged();
                this.OnPropertyChanged("ActionClassName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ActionClassName;
        partial void OnActionClassNameChanging(string value);
        partial void OnActionClassNameChanged();
        /// <summary>
        /// There are no comments for Property DependentProductNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string DependentProductNumber
        {
            get
            {
                return this._DependentProductNumber;
            }
            set
            {
                this.OnDependentProductNumberChanging(value);
                this._DependentProductNumber = value;
                this.OnDependentProductNumberChanged();
                this.OnPropertyChanged("DependentProductNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DependentProductNumber;
        partial void OnDependentProductNumberChanging(string value);
        partial void OnDependentProductNumberChanged();
        /// <summary>
        /// There are no comments for Property DependencyLegalEntityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string DependencyLegalEntityId
        {
            get
            {
                return this._DependencyLegalEntityId;
            }
            set
            {
                this.OnDependencyLegalEntityIdChanging(value);
                this._DependencyLegalEntityId = value;
                this.OnDependencyLegalEntityIdChanged();
                this.OnPropertyChanged("DependencyLegalEntityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DependencyLegalEntityId;
        partial void OnDependencyLegalEntityIdChanging(string value);
        partial void OnDependencyLegalEntityIdChanged();
        /// <summary>
        /// There are no comments for Property DependencyTransactionDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string DependencyTransactionDescription
        {
            get
            {
                return this._DependencyTransactionDescription;
            }
            set
            {
                this.OnDependencyTransactionDescriptionChanging(value);
                this._DependencyTransactionDescription = value;
                this.OnDependencyTransactionDescriptionChanged();
                this.OnPropertyChanged("DependencyTransactionDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DependencyTransactionDescription;
        partial void OnDependencyTransactionDescriptionChanging(string value);
        partial void OnDependencyTransactionDescriptionChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string EngineeringChangeOrderNumber
        {
            get
            {
                return this._EngineeringChangeOrderNumber;
            }
            set
            {
                this.OnEngineeringChangeOrderNumberChanging(value);
                this._EngineeringChangeOrderNumber = value;
                this.OnEngineeringChangeOrderNumberChanged();
                this.OnPropertyChanged("EngineeringChangeOrderNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EngineeringChangeOrderNumber;
        partial void OnEngineeringChangeOrderNumberChanging(string value);
        partial void OnEngineeringChangeOrderNumberChanged();
        /// <summary>
        /// There are no comments for Property ProcessorPersonnelNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ProcessorPersonnelNumber
        {
            get
            {
                return this._ProcessorPersonnelNumber;
            }
            set
            {
                this.OnProcessorPersonnelNumberChanging(value);
                this._ProcessorPersonnelNumber = value;
                this.OnProcessorPersonnelNumberChanged();
                this.OnPropertyChanged("ProcessorPersonnelNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ProcessorPersonnelNumber;
        partial void OnProcessorPersonnelNumberChanging(string value);
        partial void OnProcessorPersonnelNumberChanged();
        /// <summary>
        /// There are no comments for Property ActionName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ActionName
        {
            get
            {
                return this._ActionName;
            }
            set
            {
                this.OnActionNameChanging(value);
                this._ActionName = value;
                this.OnActionNameChanged();
                this.OnPropertyChanged("ActionName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ActionName;
        partial void OnActionNameChanging(string value);
        partial void OnActionNameChanged();
        /// <summary>
        /// There are no comments for Property ProcessedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset ProcessedDateTime
        {
            get
            {
                return this._ProcessedDateTime;
            }
            set
            {
                this.OnProcessedDateTimeChanging(value);
                this._ProcessedDateTime = value;
                this.OnProcessedDateTimeChanged();
                this.OnPropertyChanged("ProcessedDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _ProcessedDateTime;
        partial void OnProcessedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnProcessedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property EngineeringChangeOrderDependency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependency EngineeringChangeOrderDependency
        {
            get
            {
                return this._EngineeringChangeOrderDependency;
            }
            set
            {
                this.OnEngineeringChangeOrderDependencyChanging(value);
                this._EngineeringChangeOrderDependency = value;
                this.OnEngineeringChangeOrderDependencyChanged();
                this.OnPropertyChanged("EngineeringChangeOrderDependency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependency _EngineeringChangeOrderDependency;
        partial void OnEngineeringChangeOrderDependencyChanging(global::Microsoft.Dynamics.DataEntities.EngineeringChangeOrderDependency value);
        partial void OnEngineeringChangeOrderDependencyChanged();
        /// <summary>
        /// There are no comments for Property ProcessorWorker in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.Worker ProcessorWorker
        {
            get
            {
                return this._ProcessorWorker;
            }
            set
            {
                this.OnProcessorWorkerChanging(value);
                this._ProcessorWorker = value;
                this.OnProcessorWorkerChanged();
                this.OnPropertyChanged("ProcessorWorker");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.Worker _ProcessorWorker;
        partial void OnProcessorWorkerChanging(global::Microsoft.Dynamics.DataEntities.Worker value);
        partial void OnProcessorWorkerChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
