//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/6/2021 9:11:38 PM
namespace Microsoft.Dynamics.DataEntities
{
        /// <summary>
        /// There are no comments for JourneyTemplateHeaderSingle in the schema.
        /// </summary>
    public partial class JourneyTemplateHeaderSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<JourneyTemplateHeader>
    {
        /// <summary>
        /// Initialize a new JourneyTemplateHeaderSingle object.
        /// </summary>
        public JourneyTemplateHeaderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new JourneyTemplateHeaderSingle object.
        /// </summary>
        public JourneyTemplateHeaderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new JourneyTemplateHeaderSingle object.
        /// </summary>
        public JourneyTemplateHeaderSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<JourneyTemplateHeader> query)
            : base(query) {}

    }
        /// <summary>
        /// There are no comments for JourneyTemplateHeader in the schema.
        /// </summary>
    /// <KeyProperties>
    /// dataAreaId
    /// TemplateId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "TemplateId")]
    [global::Microsoft.OData.Client.EntitySet("JourneyTemplateHeaders")]
    public partial class JourneyTemplateHeader : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new JourneyTemplateHeader object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of dataAreaId.</param>
        /// <param name="templateId">Initial value of TemplateId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static JourneyTemplateHeader CreateJourneyTemplateHeader(string dataAreaId, string templateId)
        {
            JourneyTemplateHeader journeyTemplateHeader = new JourneyTemplateHeader();
            journeyTemplateHeader.dataAreaId = dataAreaId;
            journeyTemplateHeader.TemplateId = templateId;
            return journeyTemplateHeader;
        }
        /// <summary>
        /// There are no comments for Property dataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string dataAreaId
        {
            get
            {
                return this._dataAreaId;
            }
            set
            {
                this.OndataAreaIdChanging(value);
                this._dataAreaId = value;
                this.OndataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _dataAreaId;
        partial void OndataAreaIdChanging(string value);
        partial void OndataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property TemplateId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TemplateId
        {
            get
            {
                return this._TemplateId;
            }
            set
            {
                this.OnTemplateIdChanging(value);
                this._TemplateId = value;
                this.OnTemplateIdChanged();
                this.OnPropertyChanged("TemplateId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TemplateId;
        partial void OnTemplateIdChanging(string value);
        partial void OnTemplateIdChanged();
        /// <summary>
        /// There are no comments for Property TemplateDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TemplateDescription
        {
            get
            {
                return this._TemplateDescription;
            }
            set
            {
                this.OnTemplateDescriptionChanging(value);
                this._TemplateDescription = value;
                this.OnTemplateDescriptionChanged();
                this.OnPropertyChanged("TemplateDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TemplateDescription;
        partial void OnTemplateDescriptionChanging(string value);
        partial void OnTemplateDescriptionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
