//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/28/2021 8:55:09 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for KittingParametersSingle in the schema.
    /// </summary>
    public partial class KittingParametersSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<KittingParameters>
    {
        /// <summary>
        /// Initialize a new KittingParametersSingle object.
        /// </summary>
        public KittingParametersSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new KittingParametersSingle object.
        /// </summary>
        public KittingParametersSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new KittingParametersSingle object.
        /// </summary>
        public KittingParametersSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<KittingParameters> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for KittingParameters in the schema.
    /// </summary>
    /// <KeyProperties>
    /// dataAreaId
    /// ValidFor
    /// ItemRelation
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "ValidFor", "ItemRelation")]
    [global::Microsoft.OData.Client.EntitySet("KittingParameters")]
    public partial class KittingParameters : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new KittingParameters object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of dataAreaId.</param>
        /// <param name="itemRelation">Initial value of ItemRelation.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static KittingParameters CreateKittingParameters(string dataAreaId, string itemRelation)
        {
            KittingParameters kittingParameters = new KittingParameters();
            kittingParameters.dataAreaId = dataAreaId;
            kittingParameters.ItemRelation = itemRelation;
            return kittingParameters;
        }
        /// <summary>
        /// There are no comments for Property dataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "dataAreaId is required.")]
        public virtual string dataAreaId
        {
            get
            {
                return this._dataAreaId;
            }
            set
            {
                this.OndataAreaIdChanging(value);
                this._dataAreaId = value;
                this.OndataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _dataAreaId;
        partial void OndataAreaIdChanging(string value);
        partial void OndataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property ValidFor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.TableGroupAll> ValidFor
        {
            get
            {
                return this._ValidFor;
            }
            set
            {
                this.OnValidForChanging(value);
                this._ValidFor = value;
                this.OnValidForChanged();
                this.OnPropertyChanged("ValidFor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.TableGroupAll> _ValidFor;
        partial void OnValidForChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.TableGroupAll> value);
        partial void OnValidForChanged();
        /// <summary>
        /// There are no comments for Property ItemRelation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ItemRelation is required.")]
        public virtual string ItemRelation
        {
            get
            {
                return this._ItemRelation;
            }
            set
            {
                this.OnItemRelationChanging(value);
                this._ItemRelation = value;
                this.OnItemRelationChanged();
                this.OnPropertyChanged("ItemRelation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ItemRelation;
        partial void OnItemRelationChanging(string value);
        partial void OnItemRelationChanged();
        /// <summary>
        /// There are no comments for Property UseKitFinancialDimensions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> UseKitFinancialDimensions
        {
            get
            {
                return this._UseKitFinancialDimensions;
            }
            set
            {
                this.OnUseKitFinancialDimensionsChanging(value);
                this._UseKitFinancialDimensions = value;
                this.OnUseKitFinancialDimensionsChanged();
                this.OnPropertyChanged("UseKitFinancialDimensions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _UseKitFinancialDimensions;
        partial void OnUseKitFinancialDimensionsChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnUseKitFinancialDimensionsChanged();
        /// <summary>
        /// There are no comments for Property PartPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> PartPrice
        {
            get
            {
                return this._PartPrice;
            }
            set
            {
                this.OnPartPriceChanging(value);
                this._PartPrice = value;
                this.OnPartPriceChanged();
                this.OnPropertyChanged("PartPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _PartPrice;
        partial void OnPartPriceChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnPartPriceChanged();
        /// <summary>
        /// There are no comments for Property PartialReturn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> PartialReturn
        {
            get
            {
                return this._PartialReturn;
            }
            set
            {
                this.OnPartialReturnChanging(value);
                this._PartialReturn = value;
                this.OnPartialReturnChanged();
                this.OnPropertyChanged("PartialReturn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _PartialReturn;
        partial void OnPartialReturnChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnPartialReturnChanged();
        /// <summary>
        /// There are no comments for Property UseKitTradeAgreement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> UseKitTradeAgreement
        {
            get
            {
                return this._UseKitTradeAgreement;
            }
            set
            {
                this.OnUseKitTradeAgreementChanging(value);
                this._UseKitTradeAgreement = value;
                this.OnUseKitTradeAgreementChanged();
                this.OnPropertyChanged("UseKitTradeAgreement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _UseKitTradeAgreement;
        partial void OnUseKitTradeAgreementChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnUseKitTradeAgreementChanged();
        /// <summary>
        /// There are no comments for Property PartialDelivery in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> PartialDelivery
        {
            get
            {
                return this._PartialDelivery;
            }
            set
            {
                this.OnPartialDeliveryChanging(value);
                this._PartialDelivery = value;
                this.OnPartialDeliveryChanged();
                this.OnPropertyChanged("PartialDelivery");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _PartialDelivery;
        partial void OnPartialDeliveryChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnPartialDeliveryChanged();
        /// <summary>
        /// There are no comments for Property ReserveItemsAutomatically in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> ReserveItemsAutomatically
        {
            get
            {
                return this._ReserveItemsAutomatically;
            }
            set
            {
                this.OnReserveItemsAutomaticallyChanging(value);
                this._ReserveItemsAutomatically = value;
                this.OnReserveItemsAutomaticallyChanged();
                this.OnPropertyChanged("ReserveItemsAutomatically");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _ReserveItemsAutomatically;
        partial void OnReserveItemsAutomaticallyChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnReserveItemsAutomaticallyChanged();
        /// <summary>
        /// There are no comments for Property SetUpStorageDimensions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> SetUpStorageDimensions
        {
            get
            {
                return this._SetUpStorageDimensions;
            }
            set
            {
                this.OnSetUpStorageDimensionsChanging(value);
                this._SetUpStorageDimensions = value;
                this.OnSetUpStorageDimensionsChanged();
                this.OnPropertyChanged("SetUpStorageDimensions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _SetUpStorageDimensions;
        partial void OnSetUpStorageDimensionsChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnSetUpStorageDimensionsChanged();
        /// <summary>
        /// There are no comments for Property ManualPosting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> ManualPosting
        {
            get
            {
                return this._ManualPosting;
            }
            set
            {
                this.OnManualPostingChanging(value);
                this._ManualPosting = value;
                this.OnManualPostingChanged();
                this.OnPropertyChanged("ManualPosting");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _ManualPosting;
        partial void OnManualPostingChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnManualPostingChanged();
        /// <summary>
        /// There are no comments for Property CompleteKitCheck in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.KittingCheckPickingListRegistration> CompleteKitCheck
        {
            get
            {
                return this._CompleteKitCheck;
            }
            set
            {
                this.OnCompleteKitCheckChanging(value);
                this._CompleteKitCheck = value;
                this.OnCompleteKitCheckChanged();
                this.OnPropertyChanged("CompleteKitCheck");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.KittingCheckPickingListRegistration> _CompleteKitCheck;
        partial void OnCompleteKitCheckChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.KittingCheckPickingListRegistration> value);
        partial void OnCompleteKitCheckChanged();
        /// <summary>
        /// There are no comments for Property SetUpProductDimensions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> SetUpProductDimensions
        {
            get
            {
                return this._SetUpProductDimensions;
            }
            set
            {
                this.OnSetUpProductDimensionsChanging(value);
                this._SetUpProductDimensions = value;
                this.OnSetUpProductDimensionsChanged();
                this.OnPropertyChanged("SetUpProductDimensions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _SetUpProductDimensions;
        partial void OnSetUpProductDimensionsChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnSetUpProductDimensionsChanged();
        /// <summary>
        /// There are no comments for Property ReserveCompleteKits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> ReserveCompleteKits
        {
            get
            {
                return this._ReserveCompleteKits;
            }
            set
            {
                this.OnReserveCompleteKitsChanging(value);
                this._ReserveCompleteKits = value;
                this.OnReserveCompleteKitsChanged();
                this.OnPropertyChanged("ReserveCompleteKits");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _ReserveCompleteKits;
        partial void OnReserveCompleteKitsChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnReserveCompleteKitsChanged();
        /// <summary>
        /// There are no comments for Property WHSCompleteKitCheck in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.KittingCheckLoad> WHSCompleteKitCheck
        {
            get
            {
                return this._WHSCompleteKitCheck;
            }
            set
            {
                this.OnWHSCompleteKitCheckChanging(value);
                this._WHSCompleteKitCheck = value;
                this.OnWHSCompleteKitCheckChanged();
                this.OnPropertyChanged("WHSCompleteKitCheck");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.KittingCheckLoad> _WHSCompleteKitCheck;
        partial void OnWHSCompleteKitCheckChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.KittingCheckLoad> value);
        partial void OnWHSCompleteKitCheckChanged();
        /// <summary>
        /// There are no comments for Property ShowKitPriceOnKit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> ShowKitPriceOnKit
        {
            get
            {
                return this._ShowKitPriceOnKit;
            }
            set
            {
                this.OnShowKitPriceOnKitChanging(value);
                this._ShowKitPriceOnKit = value;
                this.OnShowKitPriceOnKitChanged();
                this.OnPropertyChanged("ShowKitPriceOnKit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _ShowKitPriceOnKit;
        partial void OnShowKitPriceOnKitChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnShowKitPriceOnKitChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
