//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/28/2021 8:55:09 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for LeaseBookSetupSingle in the schema.
    /// </summary>
    public partial class LeaseBookSetupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LeaseBookSetup>
    {
        /// <summary>
        /// Initialize a new LeaseBookSetupSingle object.
        /// </summary>
        public LeaseBookSetupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LeaseBookSetupSingle object.
        /// </summary>
        public LeaseBookSetupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LeaseBookSetupSingle object.
        /// </summary>
        public LeaseBookSetupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LeaseBookSetup> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for LeaseBookSetup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// dataAreaId
    /// BookType
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "BookType")]
    [global::Microsoft.OData.Client.EntitySet("LeaseBooksSetup")]
    public partial class LeaseBookSetup : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LeaseBookSetup object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of dataAreaId.</param>
        /// <param name="bookType">Initial value of BookType.</param>
        /// <param name="presentValueOverFairValueBookSetUp">Initial value of PresentValueOverFairValueBookSetUp.</param>
        /// <param name="shortTermMonths">Initial value of ShortTermMonths.</param>
        /// <param name="lowValueThreshold">Initial value of LowValueThreshold.</param>
        /// <param name="leaseTermOverAssetUsefulLifeBookSetUp">Initial value of LeaseTermOverAssetUsefulLifeBookSetUp.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static LeaseBookSetup CreateLeaseBookSetup(string dataAreaId, 
                    string bookType, 
                    decimal presentValueOverFairValueBookSetUp, 
                    int shortTermMonths, 
                    decimal lowValueThreshold, 
                    decimal leaseTermOverAssetUsefulLifeBookSetUp)
        {
            LeaseBookSetup leaseBookSetup = new LeaseBookSetup();
            leaseBookSetup.dataAreaId = dataAreaId;
            leaseBookSetup.BookType = bookType;
            leaseBookSetup.PresentValueOverFairValueBookSetUp = presentValueOverFairValueBookSetUp;
            leaseBookSetup.ShortTermMonths = shortTermMonths;
            leaseBookSetup.LowValueThreshold = lowValueThreshold;
            leaseBookSetup.LeaseTermOverAssetUsefulLifeBookSetUp = leaseTermOverAssetUsefulLifeBookSetUp;
            return leaseBookSetup;
        }
        /// <summary>
        /// There are no comments for Property dataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "dataAreaId is required.")]
        public virtual string dataAreaId
        {
            get
            {
                return this._dataAreaId;
            }
            set
            {
                this.OndataAreaIdChanging(value);
                this._dataAreaId = value;
                this.OndataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _dataAreaId;
        partial void OndataAreaIdChanging(string value);
        partial void OndataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property BookType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BookType is required.")]
        public virtual string BookType
        {
            get
            {
                return this._BookType;
            }
            set
            {
                this.OnBookTypeChanging(value);
                this._BookType = value;
                this.OnBookTypeChanged();
                this.OnPropertyChanged("BookType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BookType;
        partial void OnBookTypeChanging(string value);
        partial void OnBookTypeChanged();
        /// <summary>
        /// There are no comments for Property AccountingFramework in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AssetLeaseAccountingFrameworkType> AccountingFramework
        {
            get
            {
                return this._AccountingFramework;
            }
            set
            {
                this.OnAccountingFrameworkChanging(value);
                this._AccountingFramework = value;
                this.OnAccountingFrameworkChanged();
                this.OnPropertyChanged("AccountingFramework");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AssetLeaseAccountingFrameworkType> _AccountingFramework;
        partial void OnAccountingFrameworkChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AssetLeaseAccountingFrameworkType> value);
        partial void OnAccountingFrameworkChanged();
        /// <summary>
        /// There are no comments for Property PresentValueOverFairValueBookSetUp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PresentValueOverFairValueBookSetUp is required.")]
        public virtual decimal PresentValueOverFairValueBookSetUp
        {
            get
            {
                return this._PresentValueOverFairValueBookSetUp;
            }
            set
            {
                this.OnPresentValueOverFairValueBookSetUpChanging(value);
                this._PresentValueOverFairValueBookSetUp = value;
                this.OnPresentValueOverFairValueBookSetUpChanged();
                this.OnPropertyChanged("PresentValueOverFairValueBookSetUp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _PresentValueOverFairValueBookSetUp;
        partial void OnPresentValueOverFairValueBookSetUpChanging(decimal value);
        partial void OnPresentValueOverFairValueBookSetUpChanged();
        /// <summary>
        /// There are no comments for Property PayToVendor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> PayToVendor
        {
            get
            {
                return this._PayToVendor;
            }
            set
            {
                this.OnPayToVendorChanging(value);
                this._PayToVendor = value;
                this.OnPayToVendorChanged();
                this.OnPropertyChanged("PayToVendor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _PayToVendor;
        partial void OnPayToVendorChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnPayToVendorChanged();
        /// <summary>
        /// There are no comments for Property ShortTermMonths in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ShortTermMonths is required.")]
        public virtual int ShortTermMonths
        {
            get
            {
                return this._ShortTermMonths;
            }
            set
            {
                this.OnShortTermMonthsChanging(value);
                this._ShortTermMonths = value;
                this.OnShortTermMonthsChanged();
                this.OnPropertyChanged("ShortTermMonths");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ShortTermMonths;
        partial void OnShortTermMonthsChanging(int value);
        partial void OnShortTermMonthsChanged();
        /// <summary>
        /// There are no comments for Property LowValueThreshold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LowValueThreshold is required.")]
        public virtual decimal LowValueThreshold
        {
            get
            {
                return this._LowValueThreshold;
            }
            set
            {
                this.OnLowValueThresholdChanging(value);
                this._LowValueThreshold = value;
                this.OnLowValueThresholdChanged();
                this.OnPropertyChanged("LowValueThreshold");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _LowValueThreshold;
        partial void OnLowValueThresholdChanging(decimal value);
        partial void OnLowValueThresholdChanged();
        /// <summary>
        /// There are no comments for Property Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this.OnCompanyChanging(value);
                this._Company = value;
                this.OnCompanyChanged();
                this.OnPropertyChanged("Company");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Company;
        partial void OnCompanyChanging(string value);
        partial void OnCompanyChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PostingLayer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CurrentOperationsTax> PostingLayer
        {
            get
            {
                return this._PostingLayer;
            }
            set
            {
                this.OnPostingLayerChanging(value);
                this._PostingLayer = value;
                this.OnPostingLayerChanged();
                this.OnPropertyChanged("PostingLayer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CurrentOperationsTax> _PostingLayer;
        partial void OnPostingLayerChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CurrentOperationsTax> value);
        partial void OnPostingLayerChanged();
        /// <summary>
        /// There are no comments for Property LeaseType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AssetLeaseType> LeaseType
        {
            get
            {
                return this._LeaseType;
            }
            set
            {
                this.OnLeaseTypeChanging(value);
                this._LeaseType = value;
                this.OnLeaseTypeChanged();
                this.OnPropertyChanged("LeaseType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AssetLeaseType> _LeaseType;
        partial void OnLeaseTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AssetLeaseType> value);
        partial void OnLeaseTypeChanged();
        /// <summary>
        /// There are no comments for Property LeaseTermOverAssetUsefulLifeBookSetUp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LeaseTermOverAssetUsefulLifeBookSetUp is required.")]
        public virtual decimal LeaseTermOverAssetUsefulLifeBookSetUp
        {
            get
            {
                return this._LeaseTermOverAssetUsefulLifeBookSetUp;
            }
            set
            {
                this.OnLeaseTermOverAssetUsefulLifeBookSetUpChanging(value);
                this._LeaseTermOverAssetUsefulLifeBookSetUp = value;
                this.OnLeaseTermOverAssetUsefulLifeBookSetUpChanged();
                this.OnPropertyChanged("LeaseTermOverAssetUsefulLifeBookSetUp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _LeaseTermOverAssetUsefulLifeBookSetUp;
        partial void OnLeaseTermOverAssetUsefulLifeBookSetUpChanging(decimal value);
        partial void OnLeaseTermOverAssetUsefulLifeBookSetUpChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
