//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/3/2021 8:21:45 PM
namespace Microsoft.Dynamics.DataEntities
{
        /// <summary>
        /// There are no comments for PayCycleSingle in the schema.
        /// </summary>
    public partial class PayCycleSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PayCycle>
    {
        /// <summary>
        /// Initialize a new PayCycleSingle object.
        /// </summary>
        public PayCycleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PayCycleSingle object.
        /// </summary>
        public PayCycleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PayCycleSingle object.
        /// </summary>
        public PayCycleSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PayCycle> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for PayPeriod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.PayPeriod> PayPeriod
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PayPeriod == null))
                {
                    this._PayPeriod = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.PayPeriod>(GetPath("PayPeriod"));
                }
                return this._PayPeriod;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.PayPeriod> _PayPeriod;
        /// <summary>
        /// There are no comments for PayrollPositionDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.PayrollPositionDetailSingle PayrollPositionDetail
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PayrollPositionDetail == null))
                {
                    this._PayrollPositionDetail = new global::Microsoft.Dynamics.DataEntities.PayrollPositionDetailSingle(this.Context, GetPath("PayrollPositionDetail"));
                }
                return this._PayrollPositionDetail;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.PayrollPositionDetailSingle _PayrollPositionDetail;
        /// <summary>
        /// There are no comments for PayStatement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.PayStatementHeader> PayStatement
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PayStatement == null))
                {
                    this._PayStatement = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.PayStatementHeader>(GetPath("PayStatement"));
                }
                return this._PayStatement;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.PayStatementHeader> _PayStatement;
    }
        /// <summary>
        /// There are no comments for PayCycle in the schema.
        /// </summary>
    /// <KeyProperties>
    /// PayCycleId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PayCycleId")]
    [global::Microsoft.OData.Client.EntitySet("PayCycles")]
    public partial class PayCycle : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PayCycle object.
        /// </summary>
        /// <param name="payCycleId">Initial value of PayCycleId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PayCycle CreatePayCycle(string payCycleId)
        {
            PayCycle payCycle = new PayCycle();
            payCycle.PayCycleId = payCycleId;
            return payCycle;
        }
        /// <summary>
        /// There are no comments for Property PayCycleId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string PayCycleId
        {
            get
            {
                return this._PayCycleId;
            }
            set
            {
                this.OnPayCycleIdChanging(value);
                this._PayCycleId = value;
                this.OnPayCycleIdChanged();
                this.OnPropertyChanged("PayCycleId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PayCycleId;
        partial void OnPayCycleIdChanging(string value);
        partial void OnPayCycleIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PayCycleFrequency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.PayrollTimePeriod> PayCycleFrequency
        {
            get
            {
                return this._PayCycleFrequency;
            }
            set
            {
                this.OnPayCycleFrequencyChanging(value);
                this._PayCycleFrequency = value;
                this.OnPayCycleFrequencyChanged();
                this.OnPropertyChanged("PayCycleFrequency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.PayrollTimePeriod> _PayCycleFrequency;
        partial void OnPayCycleFrequencyChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.PayrollTimePeriod> value);
        partial void OnPayCycleFrequencyChanged();
        /// <summary>
        /// There are no comments for Property PayPeriod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayPeriod> PayPeriod
        {
            get
            {
                return this._PayPeriod;
            }
            set
            {
                this.OnPayPeriodChanging(value);
                this._PayPeriod = value;
                this.OnPayPeriodChanged();
                this.OnPropertyChanged("PayPeriod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayPeriod> _PayPeriod = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayPeriod>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPayPeriodChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayPeriod> value);
        partial void OnPayPeriodChanged();
        /// <summary>
        /// There are no comments for Property PayrollPositionDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.PayrollPositionDetail PayrollPositionDetail
        {
            get
            {
                return this._PayrollPositionDetail;
            }
            set
            {
                this.OnPayrollPositionDetailChanging(value);
                this._PayrollPositionDetail = value;
                this.OnPayrollPositionDetailChanged();
                this.OnPropertyChanged("PayrollPositionDetail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.PayrollPositionDetail _PayrollPositionDetail;
        partial void OnPayrollPositionDetailChanging(global::Microsoft.Dynamics.DataEntities.PayrollPositionDetail value);
        partial void OnPayrollPositionDetailChanged();
        /// <summary>
        /// There are no comments for Property PayStatement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayStatementHeader> PayStatement
        {
            get
            {
                return this._PayStatement;
            }
            set
            {
                this.OnPayStatementChanging(value);
                this._PayStatement = value;
                this.OnPayStatementChanged();
                this.OnPropertyChanged("PayStatement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayStatementHeader> _PayStatement = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayStatementHeader>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPayStatementChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayStatementHeader> value);
        partial void OnPayStatementChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
