//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12/8/2020 7:45:22 PM
namespace Microsoft.Dynamics.DataEntities
{
        /// <summary>
        /// There are no comments for RetailTillLayoutZoneSingle in the schema.
        /// </summary>
    public partial class RetailTillLayoutZoneSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RetailTillLayoutZone>
    {
        /// <summary>
        /// Initialize a new RetailTillLayoutZoneSingle object.
        /// </summary>
        public RetailTillLayoutZoneSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RetailTillLayoutZoneSingle object.
        /// </summary>
        public RetailTillLayoutZoneSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RetailTillLayoutZoneSingle object.
        /// </summary>
        public RetailTillLayoutZoneSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RetailTillLayoutZone> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for RetailTillLayoutButtonGridZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone> RetailTillLayoutButtonGridZone
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RetailTillLayoutButtonGridZone == null))
                {
                    this._RetailTillLayoutButtonGridZone = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone>(GetPath("RetailTillLayoutButtonGridZone"));
                }
                return this._RetailTillLayoutButtonGridZone;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone> _RetailTillLayoutButtonGridZone;
        /// <summary>
        /// There are no comments for RetailTillLayoutImageZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone> RetailTillLayoutImageZone
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RetailTillLayoutImageZone == null))
                {
                    this._RetailTillLayoutImageZone = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone>(GetPath("RetailTillLayoutImageZone"));
                }
                return this._RetailTillLayoutImageZone;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone> _RetailTillLayoutImageZone;
        /// <summary>
        /// There are no comments for RetailTillLayoutReportZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone> RetailTillLayoutReportZone
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RetailTillLayoutReportZone == null))
                {
                    this._RetailTillLayoutReportZone = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone>(GetPath("RetailTillLayoutReportZone"));
                }
                return this._RetailTillLayoutReportZone;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone> _RetailTillLayoutReportZone;
        /// <summary>
        /// There are no comments for DeviceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.DeviceTypeSingle DeviceTypes
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._DeviceTypes == null))
                {
                    this._DeviceTypes = new global::Microsoft.Dynamics.DataEntities.DeviceTypeSingle(this.Context, GetPath("DeviceTypes"));
                }
                return this._DeviceTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.DeviceTypeSingle _DeviceTypes;
    }
        /// <summary>
        /// There are no comments for RetailTillLayoutZone in the schema.
        /// </summary>
    /// <KeyProperties>
    /// DeviceType
    /// ZoneType
    /// ZoneId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("DeviceType", "ZoneType", "ZoneId")]
    [global::Microsoft.OData.Client.EntitySet("RetailTillLayoutZones")]
    public partial class RetailTillLayoutZone : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RetailTillLayoutZone object.
        /// </summary>
        /// <param name="deviceType">Initial value of DeviceType.</param>
        /// <param name="zoneId">Initial value of ZoneId.</param>
        /// <param name="deviceTypes">Initial value of DeviceTypes.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RetailTillLayoutZone CreateRetailTillLayoutZone(int deviceType, string zoneId, global::Microsoft.Dynamics.DataEntities.DeviceType deviceTypes)
        {
            RetailTillLayoutZone retailTillLayoutZone = new RetailTillLayoutZone();
            retailTillLayoutZone.DeviceType = deviceType;
            retailTillLayoutZone.ZoneId = zoneId;
            if ((deviceTypes == null))
            {
                throw new global::System.ArgumentNullException("deviceTypes");
            }
            retailTillLayoutZone.DeviceTypes = deviceTypes;
            return retailTillLayoutZone;
        }
        /// <summary>
        /// There are no comments for Property DeviceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int DeviceType
        {
            get
            {
                return this._DeviceType;
            }
            set
            {
                this.OnDeviceTypeChanging(value);
                this._DeviceType = value;
                this.OnDeviceTypeChanged();
                this.OnPropertyChanged("DeviceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _DeviceType;
        partial void OnDeviceTypeChanging(int value);
        partial void OnDeviceTypeChanged();
        /// <summary>
        /// There are no comments for Property ZoneType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RetailZoneType> ZoneType
        {
            get
            {
                return this._ZoneType;
            }
            set
            {
                this.OnZoneTypeChanging(value);
                this._ZoneType = value;
                this.OnZoneTypeChanged();
                this.OnPropertyChanged("ZoneType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RetailZoneType> _ZoneType;
        partial void OnZoneTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RetailZoneType> value);
        partial void OnZoneTypeChanged();
        /// <summary>
        /// There are no comments for Property ZoneId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ZoneId
        {
            get
            {
                return this._ZoneId;
            }
            set
            {
                this.OnZoneIdChanging(value);
                this._ZoneId = value;
                this.OnZoneIdChanged();
                this.OnPropertyChanged("ZoneId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ZoneId;
        partial void OnZoneIdChanging(string value);
        partial void OnZoneIdChanged();
        /// <summary>
        /// There are no comments for Property ZoneName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ZoneName
        {
            get
            {
                return this._ZoneName;
            }
            set
            {
                this.OnZoneNameChanging(value);
                this._ZoneName = value;
                this.OnZoneNameChanged();
                this.OnPropertyChanged("ZoneName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ZoneName;
        partial void OnZoneNameChanging(string value);
        partial void OnZoneNameChanged();
        /// <summary>
        /// There are no comments for Property LayoutType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RetailLayoutType> LayoutType
        {
            get
            {
                return this._LayoutType;
            }
            set
            {
                this.OnLayoutTypeChanging(value);
                this._LayoutType = value;
                this.OnLayoutTypeChanged();
                this.OnPropertyChanged("LayoutType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RetailLayoutType> _LayoutType;
        partial void OnLayoutTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.RetailLayoutType> value);
        partial void OnLayoutTypeChanged();
        /// <summary>
        /// There are no comments for Property RetailTillLayoutButtonGridZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone> RetailTillLayoutButtonGridZone
        {
            get
            {
                return this._RetailTillLayoutButtonGridZone;
            }
            set
            {
                this.OnRetailTillLayoutButtonGridZoneChanging(value);
                this._RetailTillLayoutButtonGridZone = value;
                this.OnRetailTillLayoutButtonGridZoneChanged();
                this.OnPropertyChanged("RetailTillLayoutButtonGridZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone> _RetailTillLayoutButtonGridZone = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRetailTillLayoutButtonGridZoneChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutButtonGridZone> value);
        partial void OnRetailTillLayoutButtonGridZoneChanged();
        /// <summary>
        /// There are no comments for Property RetailTillLayoutImageZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone> RetailTillLayoutImageZone
        {
            get
            {
                return this._RetailTillLayoutImageZone;
            }
            set
            {
                this.OnRetailTillLayoutImageZoneChanging(value);
                this._RetailTillLayoutImageZone = value;
                this.OnRetailTillLayoutImageZoneChanged();
                this.OnPropertyChanged("RetailTillLayoutImageZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone> _RetailTillLayoutImageZone = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRetailTillLayoutImageZoneChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutImageZone> value);
        partial void OnRetailTillLayoutImageZoneChanged();
        /// <summary>
        /// There are no comments for Property RetailTillLayoutReportZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone> RetailTillLayoutReportZone
        {
            get
            {
                return this._RetailTillLayoutReportZone;
            }
            set
            {
                this.OnRetailTillLayoutReportZoneChanging(value);
                this._RetailTillLayoutReportZone = value;
                this.OnRetailTillLayoutReportZoneChanged();
                this.OnPropertyChanged("RetailTillLayoutReportZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone> _RetailTillLayoutReportZone = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRetailTillLayoutReportZoneChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.RetailTillLayoutReportZone> value);
        partial void OnRetailTillLayoutReportZoneChanged();
        /// <summary>
        /// There are no comments for Property DeviceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.Dynamics.DataEntities.DeviceType DeviceTypes
        {
            get
            {
                return this._DeviceTypes;
            }
            set
            {
                this.OnDeviceTypesChanging(value);
                this._DeviceTypes = value;
                this.OnDeviceTypesChanged();
                this.OnPropertyChanged("DeviceTypes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.DeviceType _DeviceTypes;
        partial void OnDeviceTypesChanging(global::Microsoft.Dynamics.DataEntities.DeviceType value);
        partial void OnDeviceTypesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
