//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 6/6/2021 9:11:38 PM
namespace Microsoft.Dynamics.DataEntities
{
        /// <summary>
        /// There are no comments for TAMRebateDealWorkflowState in the schema.
        /// </summary>
    public enum TAMRebateDealWorkflowState
    {
        Draft = 0,
        Submitted = 1,
        ApprovalPending = 2,
        ApprovalDenied = 3,
        ApprovalApproved = 4,
        ChangeRequested = 7,
        Cancelled = 8,
        Completed = 9
    }
}
