//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/4/2020 2:55:10 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for AssetAccrualCalendar in the schema.
    /// </summary>
    public enum AssetAccrualCalendar
    {
        Yearly = 0,
        Monthly = 1,
        Quarterly = 2,
        HalfYearly = 3,
        Daily = 4
    }
}
