//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 9/11/2020 3:24:26 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for AssetImpairmentSharedAssetAllocBasis_JP in the schema.
    /// </summary>
    public enum AssetImpairmentSharedAssetAllocBasis_JP
    {
        NBVSubNetSellPrice = 0,
        NBV = 1
    }
}
