//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 9/11/2020 3:24:26 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for ExchangeRateCurrencyPairSingle in the schema.
    /// </summary>
    public partial class ExchangeRateCurrencyPairSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ExchangeRateCurrencyPair>
    {
        /// <summary>
        /// Initialize a new ExchangeRateCurrencyPairSingle object.
        /// </summary>
        public ExchangeRateCurrencyPairSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ExchangeRateCurrencyPairSingle object.
        /// </summary>
        public ExchangeRateCurrencyPairSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ExchangeRateCurrencyPairSingle object.
        /// </summary>
        public ExchangeRateCurrencyPairSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ExchangeRateCurrencyPair> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ExchangeRateCurrencyPair in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FromCurrencyCode
    /// ToCurrencyCode
    /// ExchangeRateTypeName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("FromCurrencyCode", "ToCurrencyCode", "ExchangeRateTypeName")]
    [global::Microsoft.OData.Client.EntitySet("ExchangeRateCurrencyPairs")]
    public partial class ExchangeRateCurrencyPair : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ExchangeRateCurrencyPair object.
        /// </summary>
        /// <param name="fromCurrencyCode">Initial value of FromCurrencyCode.</param>
        /// <param name="toCurrencyCode">Initial value of ToCurrencyCode.</param>
        /// <param name="exchangeRateTypeName">Initial value of ExchangeRateTypeName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ExchangeRateCurrencyPair CreateExchangeRateCurrencyPair(string fromCurrencyCode, string toCurrencyCode, string exchangeRateTypeName)
        {
            ExchangeRateCurrencyPair exchangeRateCurrencyPair = new ExchangeRateCurrencyPair();
            exchangeRateCurrencyPair.FromCurrencyCode = fromCurrencyCode;
            exchangeRateCurrencyPair.ToCurrencyCode = toCurrencyCode;
            exchangeRateCurrencyPair.ExchangeRateTypeName = exchangeRateTypeName;
            return exchangeRateCurrencyPair;
        }
        /// <summary>
        /// There are no comments for Property FromCurrencyCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string FromCurrencyCode
        {
            get
            {
                return this._FromCurrencyCode;
            }
            set
            {
                this.OnFromCurrencyCodeChanging(value);
                this._FromCurrencyCode = value;
                this.OnFromCurrencyCodeChanged();
                this.OnPropertyChanged("FromCurrencyCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FromCurrencyCode;
        partial void OnFromCurrencyCodeChanging(string value);
        partial void OnFromCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property ToCurrencyCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ToCurrencyCode
        {
            get
            {
                return this._ToCurrencyCode;
            }
            set
            {
                this.OnToCurrencyCodeChanging(value);
                this._ToCurrencyCode = value;
                this.OnToCurrencyCodeChanged();
                this.OnPropertyChanged("ToCurrencyCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ToCurrencyCode;
        partial void OnToCurrencyCodeChanging(string value);
        partial void OnToCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property ExchangeRateTypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ExchangeRateTypeName
        {
            get
            {
                return this._ExchangeRateTypeName;
            }
            set
            {
                this.OnExchangeRateTypeNameChanging(value);
                this._ExchangeRateTypeName = value;
                this.OnExchangeRateTypeNameChanged();
                this.OnPropertyChanged("ExchangeRateTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ExchangeRateTypeName;
        partial void OnExchangeRateTypeNameChanging(string value);
        partial void OnExchangeRateTypeNameChanged();
        /// <summary>
        /// There are no comments for Property ExchangeRateDisplayFactor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ExchangeRateDisplayFactor> ExchangeRateDisplayFactor
        {
            get
            {
                return this._ExchangeRateDisplayFactor;
            }
            set
            {
                this.OnExchangeRateDisplayFactorChanging(value);
                this._ExchangeRateDisplayFactor = value;
                this.OnExchangeRateDisplayFactorChanged();
                this.OnPropertyChanged("ExchangeRateDisplayFactor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ExchangeRateDisplayFactor> _ExchangeRateDisplayFactor;
        partial void OnExchangeRateDisplayFactorChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ExchangeRateDisplayFactor> value);
        partial void OnExchangeRateDisplayFactorChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
