//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 9/11/2020 3:24:26 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for WorkerSkillSingle in the schema.
    /// </summary>
    public partial class WorkerSkillSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<WorkerSkill>
    {
        /// <summary>
        /// Initialize a new WorkerSkillSingle object.
        /// </summary>
        public WorkerSkillSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new WorkerSkillSingle object.
        /// </summary>
        public WorkerSkillSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new WorkerSkillSingle object.
        /// </summary>
        public WorkerSkillSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<WorkerSkill> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for WorkerSkill in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonnelNumber
    /// LevelType
    /// SkillId
    /// LevelDate
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PersonnelNumber", "LevelType", "SkillId", "LevelDate")]
    [global::Microsoft.OData.Client.EntitySet("WorkerSkills")]
    public partial class WorkerSkill : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WorkerSkill object.
        /// </summary>
        /// <param name="personnelNumber">Initial value of PersonnelNumber.</param>
        /// <param name="skillId">Initial value of SkillId.</param>
        /// <param name="levelDate">Initial value of LevelDate.</param>
        /// <param name="yearsOfExperience">Initial value of YearsOfExperience.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static WorkerSkill CreateWorkerSkill(string personnelNumber, string skillId, global::System.DateTimeOffset levelDate, decimal yearsOfExperience)
        {
            WorkerSkill workerSkill = new WorkerSkill();
            workerSkill.PersonnelNumber = personnelNumber;
            workerSkill.SkillId = skillId;
            workerSkill.LevelDate = levelDate;
            workerSkill.YearsOfExperience = yearsOfExperience;
            return workerSkill;
        }
        /// <summary>
        /// There are no comments for Property PersonnelNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string PersonnelNumber
        {
            get
            {
                return this._PersonnelNumber;
            }
            set
            {
                this.OnPersonnelNumberChanging(value);
                this._PersonnelNumber = value;
                this.OnPersonnelNumberChanged();
                this.OnPropertyChanged("PersonnelNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PersonnelNumber;
        partial void OnPersonnelNumberChanging(string value);
        partial void OnPersonnelNumberChanged();
        /// <summary>
        /// There are no comments for Property LevelType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.HrmSkillLevelType> LevelType
        {
            get
            {
                return this._LevelType;
            }
            set
            {
                this.OnLevelTypeChanging(value);
                this._LevelType = value;
                this.OnLevelTypeChanged();
                this.OnPropertyChanged("LevelType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.HrmSkillLevelType> _LevelType;
        partial void OnLevelTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.HrmSkillLevelType> value);
        partial void OnLevelTypeChanged();
        /// <summary>
        /// There are no comments for Property SkillId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string SkillId
        {
            get
            {
                return this._SkillId;
            }
            set
            {
                this.OnSkillIdChanging(value);
                this._SkillId = value;
                this.OnSkillIdChanged();
                this.OnPropertyChanged("SkillId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SkillId;
        partial void OnSkillIdChanging(string value);
        partial void OnSkillIdChanged();
        /// <summary>
        /// There are no comments for Property LevelDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset LevelDate
        {
            get
            {
                return this._LevelDate;
            }
            set
            {
                this.OnLevelDateChanging(value);
                this._LevelDate = value;
                this.OnLevelDateChanged();
                this.OnPropertyChanged("LevelDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _LevelDate;
        partial void OnLevelDateChanging(global::System.DateTimeOffset value);
        partial void OnLevelDateChanged();
        /// <summary>
        /// There are no comments for Property RatingLevelExaminer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string RatingLevelExaminer
        {
            get
            {
                return this._RatingLevelExaminer;
            }
            set
            {
                this.OnRatingLevelExaminerChanging(value);
                this._RatingLevelExaminer = value;
                this.OnRatingLevelExaminerChanged();
                this.OnPropertyChanged("RatingLevelExaminer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RatingLevelExaminer;
        partial void OnRatingLevelExaminerChanging(string value);
        partial void OnRatingLevelExaminerChanged();
        /// <summary>
        /// There are no comments for Property YearsOfExperience in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual decimal YearsOfExperience
        {
            get
            {
                return this._YearsOfExperience;
            }
            set
            {
                this.OnYearsOfExperienceChanging(value);
                this._YearsOfExperience = value;
                this.OnYearsOfExperienceChanged();
                this.OnPropertyChanged("YearsOfExperience");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _YearsOfExperience;
        partial void OnYearsOfExperienceChanging(decimal value);
        partial void OnYearsOfExperienceChanged();
        /// <summary>
        /// There are no comments for Property LevelId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string LevelId
        {
            get
            {
                return this._LevelId;
            }
            set
            {
                this.OnLevelIdChanging(value);
                this._LevelId = value;
                this.OnLevelIdChanged();
                this.OnPropertyChanged("LevelId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LevelId;
        partial void OnLevelIdChanging(string value);
        partial void OnLevelIdChanged();
        /// <summary>
        /// There are no comments for Property RatingId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string RatingId
        {
            get
            {
                return this._RatingId;
            }
            set
            {
                this.OnRatingIdChanging(value);
                this._RatingId = value;
                this.OnRatingIdChanged();
                this.OnPropertyChanged("RatingId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RatingId;
        partial void OnRatingIdChanging(string value);
        partial void OnRatingIdChanged();
        /// <summary>
        /// There are no comments for Property Verified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> Verified
        {
            get
            {
                return this._Verified;
            }
            set
            {
                this.OnVerifiedChanging(value);
                this._Verified = value;
                this.OnVerifiedChanged();
                this.OnPropertyChanged("Verified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _Verified;
        partial void OnVerifiedChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnVerifiedChanged();
        /// <summary>
        /// There are no comments for Property Certifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Certifier
        {
            get
            {
                return this._Certifier;
            }
            set
            {
                this.OnCertifierChanging(value);
                this._Certifier = value;
                this.OnCertifierChanged();
                this.OnPropertyChanged("Certifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Certifier;
        partial void OnCertifierChanging(string value);
        partial void OnCertifierChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
