//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/4/2020 2:55:10 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for PayrollGenerationSource in the schema.
    /// </summary>
    public enum PayrollGenerationSource
    {
        UserEntry = 1,
        Recurring = 2,
        Salary = 3,
        Imported = 4,
        WorkerLeave = 5,
        PositionSchedule = 6,
        Retroactive = 7,
        Premium = 8
    }
}
